apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 1ef43c37d792750612ba0e882c5f9f4fc5e72563dbb0aad4890803f0acaa9aab
    cni.projectcalico.org/podIP: 10.250.40.212/32
    cni.projectcalico.org/podIPs: 10.250.40.212/32
    kubectl.kubernetes.io/restartedAt: "2026-07-31T01:26:29+08:00"
  creationTimestamp: "2026-07-30T17:26:29Z"
  generateName: mooncake-master-deployment-5445f6b5c5-
  generation: 1
  labels:
    app: mooncake-master
    pod-template-hash: 5445f6b5c5
  name: mooncake-master-deployment-5445f6b5c5-j2fzn
  namespace: liangjiahao
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: mooncake-master-deployment-5445f6b5c5
    uid: d88be915-2d0a-47ed-9541-9b54423857ca
  resourceVersion: "26390821"
  uid: 2dfe74f3-0234-4423-90fc-745da67fb9ab
spec:
  containers:
  - args:
    - exec mooncake_master --rpc_port=50001 --metrics_port=9003 --default_kv_lease_ttl=30s
      --enable_offload=false --logtostderr=true
    command:
    - /bin/bash
    - -lc
    image: docker.io/library/vllm-ascend:kv-pool-layerwise-v0.25.1-a2-14beaf16-20260730T130225Z-r4
    imagePullPolicy: Never
    name: mooncake-master
    ports:
    - containerPort: 50001
      name: master-rpc
      protocol: TCP
    - containerPort: 9003
      name: metrics
      protocol: TCP
    readinessProbe:
      failureThreshold: 20
      initialDelaySeconds: 2
      periodSeconds: 3
      successThreshold: 1
      tcpSocket:
        port: master-rpc
      timeoutSeconds: 1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-pcqjq
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: n1
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 30
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 30
  volumes:
  - name: kube-api-access-pcqjq
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-07-30T17:26:30Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-07-30T17:26:29Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-07-30T17:26:34Z"
    observedGeneration: 1
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-07-30T17:26:34Z"
    observedGeneration: 1
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-07-30T17:26:29Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://e980fe8c71fe50523a174382756c2b3a039ba7dbf6c1a0a431bb19b1f29948da
    image: docker.io/library/vllm-ascend:kv-pool-layerwise-v0.25.1-a2-14beaf16-20260730T130225Z-r4
    imageID: sha256:60ef6bbf63d353e4d3f06057a8b8eb53233bb4f6942a7f8466c35081cf87a358
    lastState: {}
    name: mooncake-master
    ready: true
    resources: {}
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-07-30T17:26:30Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        uid: 0
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-pcqjq
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.200.27
  hostIPs:
  - ip: 192.168.200.27
  observedGeneration: 1
  phase: Running
  podIP: 10.250.40.212
  podIPs:
  - ip: 10.250.40.212
  qosClass: BestEffort
  startTime: "2026-07-30T17:26:29Z"
