apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"mooncake-master-service","namespace":"liangjiahao"},"spec":{"ports":[{"name":"master-rpc","port":30089,"protocol":"TCP","targetPort":"master-rpc"},{"name":"metrics","port":9003,"protocol":"TCP","targetPort":"metrics"}],"selector":{"app":"mooncake-master"},"type":"ClusterIP"}}
    creationTimestamp: "2026-07-30T17:08:15Z"
    name: mooncake-master-service
    namespace: liangjiahao
    resourceVersion: "26380472"
    uid: 1943a627-3a4a-4bbc-8dca-70ba318429bd
  spec:
    clusterIP: 10.96.5.121
    clusterIPs:
    - 10.96.5.121
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: master-rpc
      port: 30089
      protocol: TCP
      targetPort: master-rpc
    - name: metrics
      port: 9003
      protocol: TCP
      targetPort: metrics
    selector:
      app: mooncake-master
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"vllm-proxy-service","namespace":"liangjiahao"},"spec":{"ports":[{"name":"http-api","port":8000,"protocol":"TCP","targetPort":"proxy-port"}],"selector":{"app":"proxy"},"type":"ClusterIP"}}
    creationTimestamp: "2026-07-30T17:08:38Z"
    name: vllm-proxy-service
    namespace: liangjiahao
    resourceVersion: "26380766"
    uid: 7fda3043-d38c-426a-831b-83923958179a
  spec:
    clusterIP: 10.96.51.130
    clusterIPs:
    - 10.96.51.130
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http-api
      port: 8000
      protocol: TCP
      targetPort: proxy-port
    selector:
      app: proxy
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
