apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      cni.projectcalico.org/containerID: 930485ef9ed7b804aeaa6ed7812364356ed4d7ad0ca82cba19baae9b8a6ee38b
      cni.projectcalico.org/podIP: 10.250.40.211/32
      cni.projectcalico.org/podIPs: 10.250.40.211/32
    creationTimestamp: "2026-07-30T17:08:38Z"
    generateName: proxy-server-deployment-54bb6c9585-
    generation: 1
    labels:
      app: proxy
      pod-template-hash: 54bb6c9585
    name: proxy-server-deployment-54bb6c9585-7fzs5
    namespace: liangjiahao
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: proxy-server-deployment-54bb6c9585
      uid: 8a99fc21-b4ff-4ffe-8930-9f2d93cc0185
    resourceVersion: "26380799"
    uid: ab1765a0-3664-45c5-82d8-391adabcb4ba
  spec:
    containers:
    - args:
      - exec python3 /app/k8s_proxy_server_example.py --host 0.0.0.0 --port 8000 --prefiller-labels
        app=prefill --decoder-labels app=decode --prefiller-container prefill-engine
        --decoder-container decode-engine --prefiller-port-name prefill-port --decoder-port-name
        decode-port --namespace liangjiahao
      command:
      - /bin/bash
      - -lc
      image: cr.openfuyao.cn/openfuyao/proxy-server:latest
      imagePullPolicy: IfNotPresent
      name: proxy-server
      ports:
      - containerPort: 8000
        name: proxy-port
        protocol: TCP
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
        requests:
          cpu: 250m
          memory: 512Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-s2qpz
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: n1
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: vllm-proxy-sa
    serviceAccountName: vllm-proxy-sa
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 30
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 30
    volumes:
    - name: kube-api-access-s2qpz
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-07-30T17:08:39Z"
      observedGeneration: 1
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-07-30T17:08:38Z"
      observedGeneration: 1
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-07-30T17:08:39Z"
      observedGeneration: 1
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-07-30T17:08:39Z"
      observedGeneration: 1
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-07-30T17:08:38Z"
      observedGeneration: 1
      status: "True"
      type: PodScheduled
    containerStatuses:
    - allocatedResources:
        cpu: 250m
        memory: 512Mi
      containerID: containerd://ce22579bd698b82cc07ea436f23d663757d253e5311f5b3de81bf3e3d07013be
      image: cr.openfuyao.cn/openfuyao/proxy-server:latest
      imageID: cr.openfuyao.cn/openfuyao/proxy-server@sha256:fa8d04696e4bcf04e0e6c2c084bb8ecefa1b85191414d66889a778750ff1e3e0
      lastState: {}
      name: proxy-server
      ready: true
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
        requests:
          cpu: 250m
          memory: 512Mi
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-07-30T17:08:39Z"
      user:
        linux:
          gid: 0
          supplementalGroups:
          - 0
          uid: 0
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-s2qpz
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 192.168.200.27
    hostIPs:
    - ip: 192.168.200.27
    observedGeneration: 1
    phase: Running
    podIP: 10.250.40.211
    podIPs:
    - ip: 10.250.40.211
    qosClass: Burstable
    startTime: "2026-07-30T17:08:38Z"
kind: List
metadata:
  resourceVersion: ""
