cli_args=dict(
    cfg_time_str='20260809_185034',
    config='/client-tools/runs/dp1-16384-bulk-o128-c8/formal-1/964c63d1f04004c1/config.py',
    config_dir='configs',
    custom_dataset_data_type=None,
    custom_dataset_infer_method=None,
    custom_dataset_meta_path=None,
    custom_dataset_path=None,
    datasets=None,
    debug=False,
    dir_time_str='20260809_185034',
    dry_run=False,
    dump_eval_details=False,
    dump_extract_rate=False,
    max_num_workers=1,
    max_workers_per_gpu=1,
    merge_ds=False,
    mode='perf',
    models=None,
    num_prompts=None,
    num_warmups=0,
    pressure=False,
    pressure_time=15,
    reuse=None,
    search=False,
    summarizer=None,
    work_dir=None)
datasets=[
    dict(abbr='bulk',
        eval_cfg=dict(
            evaluator=dict(
                type='ais_bench.benchmark.openicl.icl_evaluator.icl_hf_evaluator.AccEvaluator')),
        infer_cfg=dict(
            inferencer=dict(
                type='ais_bench.benchmark.openicl.icl_inferencer.icl_gen_inferencer.GenInferencer'),
            prompt_template=dict(
                template='{question}',
                type='ais_bench.benchmark.openicl.icl_prompt_template.icl_prompt_template.PromptTemplate'),
            retriever=dict(
                prompt_template=dict(
                    template='{question}',
                    type='ais_bench.benchmark.openicl.icl_prompt_template.icl_prompt_template.PromptTemplate'),
                type='ais_bench.benchmark.openicl.icl_retriever.icl_zero_retriever.ZeroRetriever')),
        path='/client-tools/runs/dp1-16384-bulk-o128-c8/formal-1/964c63d1f04004c1/dataset.jsonl',
        reader_cfg=dict(
            input_columns=[
                'question',
                ],
            output_column='answer'),
        type='ais_bench.benchmark.datasets.custom.CustomDataset'),
    ]
infer=dict(
    partitioner=dict(
        out_dir='/client-tools/runs/dp1-16384-bulk-o128-c8/formal-1/964c63d1f04004c1/aisbench-output/20260809_185034/predictions/',
        type='ais_bench.benchmark.partitioners.naive.NaivePartitioner'),
    runner=dict(
        debug=False,
        max_num_workers=1,
        max_workers_per_gpu=1,
        task=dict(
            type='ais_bench.benchmark.tasks.openicl_api_infer.OpenICLApiInferTask'),
        type='ais_bench.benchmark.runners.local.LocalRunner'))
mode='perf'
models=[
    dict(abbr='bulk',
        attr='service',
        batch_size=8,
        generation_kwargs=dict(
            ignore_eos=True,
            temperature=0),
        max_out_len=128,
        model='vllm-ascend/DeepSeek-V2-Lite-W8A8',
        path='/root/.cache/modelscope/vllm-ascend/DeepSeek-V2-Lite-W8A8',
        request_rate=0,
        retry=1,
        stream=True,
        type='ais_bench.benchmark.models.api_models.vllm_custom_api.VLLMCustomAPI',
        url='http://vllm-proxy-service:8000/'),
    ]
summarizer=dict(
    calculator=dict(
        stats_list=[
            'Average',
            'Min',
            'Max',
            'Median',
            'P75',
            'P90',
            'P95',
            'P99',
            ],
        type='ais_bench.benchmark.calculators.default_perf_metric_calculator.DefaultPerfMetricCalculator'),
    type='ais_bench.benchmark.summarizers.default_perf.DefaultPerfSummarizer')
work_dir='/client-tools/runs/dp1-16384-bulk-o128-c8/formal-1/964c63d1f04004c1/aisbench-output/20260809_185034'