apiVersion: apps/v1
kind: Deployment
metadata:
  name: mooncake-master-deployment
  namespace: ai-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mooncake-master
  template:
    metadata:
      labels:
        app: mooncake-master
    spec:
      nodeName: n1
      containers:
        - name: mooncake-master
          image: docker.io/library/vllm-ascend:kv-pool-layerwise-v0.24.0-a2
          imagePullPolicy: Never
          command: ["/bin/bash", "-lc"]
          args:
            - >-
              exec mooncake_master
              --rpc_port=50001
              --metrics_port=9003
              --enable_offload=false
              --logtostderr=true
          ports:
            - name: master-rpc
              containerPort: 50001
            - name: metrics
              containerPort: 9003
          readinessProbe:
            tcpSocket:
              port: master-rpc
            initialDelaySeconds: 2
            periodSeconds: 3
            failureThreshold: 20
---
apiVersion: v1
kind: Service
metadata:
  name: mooncake-master-service
  namespace: ai-inference
spec:
  type: ClusterIP
  selector:
    app: mooncake-master
  ports:
    - name: master-rpc
      protocol: TCP
      port: 30089
      targetPort: master-rpc
    - name: metrics
      protocol: TCP
      port: 9003
      targetPort: metrics
